// 中英映射表:category / equipment / target 的界面展示

export const CATEGORY_ZH: Record<string, string> = {
  'upper arms': '上臂',
  'upper legs': '大腿',
  'back': '背部',
  'waist': '腰腹',
  'chest': '胸部',
  'shoulders': '肩部',
  'lower legs': '小腿',
  'lower arms': '前臂',
  'cardio': '有氧',
  'neck': '颈部',
}

export const EQUIPMENT_ZH: Record<string, string> = {
  'body weight': '自重',
  'dumbbell': '哑铃',
  'cable': '绳索器械',
  'barbell': '杠铃',
  'leverage machine': '杠杆器械',
  'band': '弹力带',
  'smith machine': '史密斯机',
  'kettlebell': '壶铃',
  'weighted': '负重',
  'stability ball': '健身球',
  'ez barbell': '曲杆',
  'assisted': '辅助器械',
  'sled machine': '雪橇机',
  'medicine ball': '药球',
  'rope': '绳索',
  'roller': '泡沫轴',
  'resistance band': '阻力带',
  'bosu ball': '波速球',
  'olympic barbell': '奥杠',
  'wheel roller': '健腹轮',
  'upper body ergometer': '上肢测功仪',
  'skierg machine': '滑雪测功仪',
  'hammer': '大锤',
  'stationary bike': '固定单车',
  'tire': '轮胎',
  'trap bar': '陷阱杠',
  'elliptical machine': '椭圆机',
  'stepmill machine': '台阶机',
}

export const TARGET_ZH: Record<string, string> = {
  'abs': '腹肌',
  'pectorals': '胸肌',
  'biceps': '肱二头肌',
  'glutes': '臀肌',
  'delts': '三角肌',
  'triceps': '肱三头肌',
  'upper back': '上背部',
  'lats': '背阔肌',
  'calves': '小腿',
  'quads': '股四头肌',
  'forearms': '前臂',
  'cardiovascular system': '心肺',
  'hamstrings': '腘绳肌',
  'spine': '脊柱',
  'traps': '斜方肌',
  'adductors': '内收肌',
  'serratus anterior': '前锯肌',
  'abductors': '外展肌',
  'levator scapulae': '肩胛提肌',
  'adductor': '内收肌',
  'abductor': '外展肌',
  'rotator cuff': '肩袖',
  'biceps brachii': '肱二头肌',
  'triceps brachii': '肱三头肌',
  'deltoid': '三角肌',
  'gluteus maximus': '臀大肌',
  'gluteus medius': '臀中肌',
  'soleus': '比目鱼肌',
  'gastrocnemius': '腓肠肌',
  'tibialis anterior': '胫骨前肌',
  'hip flexors': '髋屈肌',
  'obliques': '腹斜肌',
  'lower back': '下背部',
  'neck': '颈部',
  'quadriceps': '股四头肌',
  'pectoralis major': '胸大肌',
  'pectoralis minor': '胸小肌',
  'anterior deltoid': '前束',
  'lateral deltoid': '中束',
  'posterior deltoid': '后束',
  'rectus abdominis': '腹直肌',
  'transverse abdominis': '腹横肌',
  'erector spinae': '竖脊肌',
  'rhomboids': '菱形肌',
  'trapezius': '斜方肌',
  'wrist flexors': '腕屈肌',
  'wrist extensors': '腕伸肌',
  'brachialis': '肱肌',
  'brachioradialis': '肱桡肌',
}

export const MUSCLE_ZH: Record<string, string> = {
  'shoulders': '肩部',
  'forearms': '前臂',
  'biceps': '肱二头肌',
  'triceps': '肱三头肌',
  'hamstrings': '腘绳肌',
  'quadriceps': '股四头肌',
  'glutes': '臀肌',
  'obliques': '腹斜肌',
  'hip flexors': '髋屈肌',
  'chest': '胸部',
  'trapezius': '斜方肌',
  'traps': '斜方肌',
  'deltoids': '三角肌',
  'calves': '小腿',
  'ankles': '脚踝',
  'lats': '背阔肌',
  'abs': '腹肌',
  'lower back': '下背部',
  'upper back': '上背部',
  'adductors': '内收肌',
  'abductors': '外展肌',
  'rotator cuff': '肩袖',
  'wrist flexors': '腕屈肌',
  'wrist extensors': '腕伸肌',
  'neck': '颈部',
  'spine': '脊柱',
  'quads': '股四头肌',
  'erector spinae': '竖脊肌',
  'pectoralis major': '胸大肌',
  'serratus anterior': '前锯肌',
  'levator scapulae': '肩胛提肌',
  'brachialis': '肱肌',
  'brachioradialis': '肱桡肌',
  'soleus': '比目鱼肌',
  'gastrocnemius': '腓肠肌',
  'tibialis anterior': '胫骨前肌',
  'peroneals': '腓骨肌',
  'piriformis': '梨状肌',
  'rectus abdominis': '腹直肌',
  'transverse abdominis': '腹横肌',
  'gluteus maximus': '臀大肌',
  'gluteus medius': '臀中肌',
  'vastus medialis': '股内侧肌',
  'vastus lateralis': '股外侧肌',
  'rectus femoris': '股直肌',
  'biceps femoris': '股二头肌',
  'semitendinosus': '半腱肌',
  'semimembranosus': '半膜肌',
  'tensor fasciae latae': '阔筋膜张肌',
  'rhomboids': '菱形肌',
  'teres major': '大圆肌',
  'teres minor': '小圆肌',
  'infraspinatus': '冈下肌',
  'supraspinatus': '冈上肌',
  'subscapularis': '肩胛下肌',
  'coracobrachialis': '喙肱肌',
  'iliopsoas': '髂腰肌',
  'psoas': '腰大肌',
  'quadratus lumborum': '腰方肌',
  'gracilis': '股薄肌',
  'sartorius': '缝匠肌',
  'popliteus': '腘肌',
  'plantaris': '跖肌',
  'flexor digitorum': '指屈肌',
  'extensor digitorum': '指伸肌',
  'flexor carpi': '腕屈肌',
  'extensor carpi': '腕伸肌',
  'palmaris longus': '掌长肌',
  'abdominals': '腹肌',
  'ankle stabilizers': '踝部稳定肌',
  'core': '核心',
  'hands': '手部',
  'latissimus dorsi': '背阔肌',
  'wrists': '手腕',
  'back': '背部',
  'feet': '脚部',
  'grip muscles': '握力肌群',
  'groin': '腹股沟',
  'inner thighs': '大腿内侧',
  'lower abs': '下腹',
  'rear deltoids': '三角肌后束',
  'shins': '胫骨',
  'sternocleidomastoid': '胸锁乳突肌',
  'upper chest': '上胸',
}

export function zh(key: string, table: Record<string, string>): string {
  return table[key] ?? key
}